version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: recruit+-
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: '%'
    command:
        --character-set-server=utf8mb4 
        --collation-server=utf8mb4_unicode_ci


